version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    environment:
      - MONGO_URL=mongodb://db:27017/homes
      - SERVER_PORT=5000
    ports:
      - '5000:5000'

  db:
    container_name: db
    image: mongo:4.2.6-bionic
    restart: always
